### ISSUE TITLE
Universal selector isn't slow by itself

### ISSUE THREAD

**Issue by Francisc** [csswizardry/CSS-Guidelines#1]
In Selectors->Performance you advise against using the universal selector (*{}).

That's actually not true if the selector is just `*{}` as that is pretty fast. As fast as an element selector some say.
What's slow is this: `div *{}` and the deeper it goes it gets even slower because of browsers reading from right to left meaning it first gets all elements, then checks which of them are inside a div for each of them, going up until the parent HTML node looking for a div.

**Comment by csswizardry** [comment]
Of course, you are correct. I shall word it a little more carefully, thanks!

**Comment by Francisc** [comment]
Just finished reading it and enjoyed it.
Thank you.
