### ISSUE TITLE
menu using these/bem guidelines

### ISSUE THREAD

**Issue by fxck** [csswizardry/CSS-Guidelines#22]
Probably not the very best place to ask this, but I tried asking on SA and got shouted at.

I've been using https://github.com/csswizardry/csswizardry-grids for a while now, and decided I wanted to recode my whole app using BEM, so I read all the articles, and decided to use the same naming conventions you are using(http://csswizardry.com/2013/01/mindbemding-getting-your-head-round-bem-syntax/) but this is not really about naming conventions.

I found all the articles lacking real life use examples. And I immediately stumbled upon a problem when trying to use BEM on the very first thing on the app, that is the navigation. 

Now consider this code, it has to be the most common thing everyone does

``` html
<ul>
    <li>
        <a href="/what">What</a>
    </li>

    <li>
        <a href="/why">Why</a>
    </li>

    <li>
        <a href="/how">How</a>
    </li>
</ul>
```

which is supposed to look, say, like this
![](http://media.smashingmagazine.com/wp-content/uploads/2012/03/menu-items2.jpg)

ul, given a class `.menu` will be the "block" now what would be the element? `li` or `a`, the obvious choice would be the `li`, but if I styled the `li`, only text would be clickable, so the more practical(and standard) choice would be the `a`.

But I'd still need to, at very least, do `.menu li { display: inline; }` .. but I'm not supposed to use element selectors in css, right? Does this fall to "you don't have to BEM everything category"? The other option would be to give the `li` some BEM class as well, like `.menu__listitem` along the class for `a` which would be `.menu_item`.. but if I decided to apply this `.menu` to any other element, which doesn't required an additional element to be semantic, like `div`&`a` combo, that `.menu__listitem` would become redundant, right. So what's the best approach?

I could probably create a handy `.display-inline` utility class a put it on each one of the `li`s, but can see this "problem" happening basicaly everytime any "block" is made by more than one nested element, whatever the reason would be, and an utility class just might not be enough..

Thank you in advance if you find a couple of minutes to read and respond to this..

**Comment by anthwinter** [comment]
You can have multiple elements within a block, for example:

<pre>
.menu {}
    .menu__list {}
    .menu__list-item {}
    .menu__link {}
</pre>

Then the html would be:

<nav class="menu">
    <ul class="menu__list">
        <li class="menu__list-item">
            <a class="menu__link">link</a>
        </li>
    </ul>
</nav>

This is the approach I have taken on a project recently.

**Comment by fxck** [comment]
Yeah, that's what I said in "The other option would be to give the li some BEM class as well, like .menu__listitem along the class for a which would be .menu_item" but then you are kind of much coupling it with html, aren't you?

On the other hand, for this particular case I could use the utility class, and the other cases I was talking about could probably be dealt with using another elements..

**Comment by csswizardry** [comment]
Hey!

If you were to use BEM, you would have:

```
.menu {}
    .menu__item {}
        .menu__link {}
```

> but then you are kind of much coupling it with html, aren't you?

The opposite :)

A selector like `.menu > li {}` is tightly coupled to the HTML in that you _have_ to use `li`s. Using a class means that, for whatever reason, that styling could be applied to anything :)

BEM can seem redundant at times, but it’s a powerful naming convention that, for the most part, works perfectly :)

**Comment by fxck** [comment]
Thanks!
