### ISSUE TITLE
Suggest to include chapter on SASS specific naming conventions

### ISSUE THREAD

**Issue by iamskok** [csswizardry/CSS-Guidelines#34]
What naming conventions do you use for: `@function`, `@mixin`, `%placeholder`, `$variable`, `$map: ('key1': value1, 'key2': value2)` and why?

**Comment by csswizardry** [comment]
Hey!

Thanks for the suggestion. I think I do need to add a Sass section, _however_… that will likely just end up being a link to @HugoGiraudel’s spin-off site _[Sass Guidelines](http://sass-guidelin.es/)_. He covers all that stuff in far more detail than I ever could :)

H

**Comment by iamskok** [comment]
@csswizardry I have just read the amazing sass-guidelin.es by @HugoGiraudel , but it doesn't cover SASS specific naming conventions. 

Will be awesome if one of you will take this responsibility and write a chapter! Cheers! :+1:

**Comment by KittyGiraudel** [comment]
I do: http://sass-guidelin.es/#naming-conventions. If you feel like something's missing, please feel free to open an issue. :)
