### ISSUE TITLE
HTTPS version of site insecure

### ISSUE THREAD

**Issue by jameskirkby** [csswizardry/CSS-Guidelines#38]
https://cssguidelin.es/

Could easily use CloudFlare like you did for your main site:
https://csswizardry.com/2017/01/moving-css-wizardry-onto-https-and-http-2/

**Comment by csswizardry** [comment]
Fixed!

**Comment by csswizardry** [comment]
[CSS Guidelines](https://cssguidelin.es/) is now a fully offline-capable PWA 😎
