### ISSUE TITLE
Why u no love spaces?

### ISSUE THREAD

**Issue by kaelig** [csswizardry/CSS-Guidelines#4]
Hi,

First of all, let me tell you that I dig your guidelines, bro. Especially about the naming conventions (dashes only, lowercase…).

On the other side, I noted that you didn't like spaces (in rules or for indentation)!

Why do you write this:

```
.selector{
  property:value;
}
```

Instead of this:

```
.selector {
  property: value;
}
```

The second example (with spaces before the bracket and after the colon) looks more readable (and is also more popular amongst developers). What do you think?

Also, I'm using spaces to indent the code, so my indentation matches HAML's and looks everywhere the same, but that's just personal taste and better for _my_ workflow. Some developers would burn people like me (@leaverou).

Thanks and keep up the good work!

**Comment by csswizardry** [comment]
It is entirely personal preference; over the last few years I have just got used to not hitting space after colons etc.

If you prefer the spaces then please, by all means use them :)

**Comment by kaelig** [comment]
Oh I will :) 

Thanks for your answer!
